name= input ("Hi whats your name?")
print(f"whats up {name} what did you do this weekend?")
answer1 = input()
print(f"{answer1} sounds like so much fun!")
print(f"{name} whats your favorite show right now??")
answer2 = input ()
print (f"omg I love {answer2} to!")
print("do you have any hobbies?")
answer3 = input()
print (f"wow {answer3} sounds really cool!")
print(f"what do you like about {answer3}?")
answer4 = input ()
print(f"oh {answer4} makes {answer3} sound really cool!")
print("how old are you?")
answer5 = input ()
print (f"I'm {answer5} to!")
print ("well it was nice talking to you!")
print("see you soon!")
